# Generated by Django 4.2.4 on 2023-09-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='product',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created At'),
        ),
    ]
